export const themes = {

  // 🌌 Dark Cosmic (Default Pixora)
  darkCosmic: {
    id: "darkCosmic",
    name: "Dark Cosmic",
    icon: "🌌",
    colors: {
      "--bg-primary": "#0A0F1C",
      "--bg-secondary": "#121A2B",
      "--bg-card": "#1A2332",
      "--bg-input": "#1F2937",
      "--text-primary": "#F8FAFC",
      "--text-secondary": "#94A3B8",
      "--accent-primary": "#00F5D4",
      "--accent-secondary": "#7C3AED",
      "--accent-highlight": "#FF2E93",
      "--border-color": "#1E293B",
      "--btn-gradient-start": "#00F5D4",
      "--btn-gradient-end": "#7C3AED",
      "--btn-glow": "rgba(124, 58, 237, 0.5)",
      "--shadow-color": "rgba(0, 245, 212, 0.1)",
      "--hover-bg": "#1E293B",
      "--success": "#10B981",
      "--error": "#EF4444",
      "--warning": "#F59E0B",
    },
  },

  // ☀️ Light Minimal
  lightMinimal: {
    id: "lightMinimal",
    name: "Light Minimal",
    icon: "☀️",
    colors: {
      "--bg-primary": "#F4F7FF",
      "--bg-secondary": "#FFFFFF",
      "--bg-card": "#FFFFFF",
      "--bg-input": "#EEF2FF",
      "--text-primary": "#0F172A",
      "--text-secondary": "#475569",
      "--accent-primary": "#7C3AED",
      "--accent-secondary": "#3B82F6",
      "--accent-highlight": "#00C2A8",
      "--border-color": "#E2E8F0",
      "--btn-gradient-start": "#7C3AED",
      "--btn-gradient-end": "#3B82F6",
      "--btn-glow": "rgba(59, 130, 246, 0.3)",
      "--shadow-color": "rgba(0, 0, 0, 0.08)",
      "--hover-bg": "#F1F5F9",
      "--success": "#059669",
      "--error": "#DC2626",
      "--warning": "#D97706",
    },
  },

  // 🧪 Acid Tech
  acidTech: {
    id: "acidTech",
    name: "Acid Tech",
    icon: "🧪",
    colors: {
      "--bg-primary": "#0A0A0A",
      "--bg-secondary": "#141414",
      "--bg-card": "#1A1A1A",
      "--bg-input": "#222222",
      "--text-primary": "#F5F5F5",
      "--text-secondary": "#888888",
      "--accent-primary": "#DFFF00",
      "--accent-secondary": "#00FF88",
      "--accent-highlight": "#FF00FF",
      "--border-color": "#2A2A2A",
      "--btn-gradient-start": "#DFFF00",
      "--btn-gradient-end": "#00FF88",
      "--btn-glow": "rgba(223, 255, 0, 0.4)",
      "--shadow-color": "rgba(223, 255, 0, 0.1)",
      "--hover-bg": "#222222",
      "--success": "#00FF88",
      "--error": "#FF4444",
      "--warning": "#FFAA00",
    },
  },

  // 🌋 Lava Core
  lavaCore: {
    id: "lavaCore",
    name: "Lava Core",
    icon: "🌋",
    colors: {
      "--bg-primary": "#1A0F0A",
      "--bg-secondary": "#241510",
      "--bg-card": "#2E1A12",
      "--bg-input": "#3A2218",
      "--text-primary": "#EAEAEA",
      "--text-secondary": "#B89080",
      "--accent-primary": "#FF4D00",
      "--accent-secondary": "#FF8C00",
      "--accent-highlight": "#FFD700",
      "--border-color": "#3A2218",
      "--btn-gradient-start": "#FF4D00",
      "--btn-gradient-end": "#FFD700",
      "--btn-glow": "rgba(255, 77, 0, 0.5)",
      "--shadow-color": "rgba(255, 77, 0, 0.15)",
      "--hover-bg": "#3A2218",
      "--success": "#22C55E",
      "--error": "#FF0000",
      "--warning": "#FFD700",
    },
  },

  // 🌊 Cyber Aqua
  cyberAqua: {
    id: "cyberAqua",
    name: "Cyber Aqua",
    icon: "🌊",
    colors: {
      "--bg-primary": "#071A1D",
      "--bg-secondary": "#0D2528",
      "--bg-card": "#123035",
      "--bg-input": "#183A40",
      "--text-primary": "#E6F1F2",
      "--text-secondary": "#7AACB0",
      "--accent-primary": "#00F5D4",
      "--accent-secondary": "#9B5DE5",
      "--accent-highlight": "#00BBF9",
      "--border-color": "#1A3F45",
      "--btn-gradient-start": "#00F5D4",
      "--btn-gradient-end": "#9B5DE5",
      "--btn-glow": "rgba(0, 245, 212, 0.4)",
      "--shadow-color": "rgba(0, 245, 212, 0.1)",
      "--hover-bg": "#183A40",
      "--success": "#00F5D4",
      "--error": "#FF6B6B",
      "--warning": "#FFC43D",
    },
  },

  // 👑 Royal Gold
  royalGold: {
    id: "royalGold",
    name: "Royal Gold",
    icon: "👑",
    colors: {
      "--bg-primary": "#121212",
      "--bg-secondary": "#1C1C1C",
      "--bg-card": "#242424",
      "--bg-input": "#2E2E2E",
      "--text-primary": "#F8F8F8",
      "--text-secondary": "#A0A0A0",
      "--accent-primary": "#D4AF37",
      "--accent-secondary": "#F5D76E",
      "--accent-highlight": "#FFE4A0",
      "--border-color": "#333333",
      "--btn-gradient-start": "#D4AF37",
      "--btn-gradient-end": "#F5D76E",
      "--btn-glow": "rgba(212, 175, 55, 0.4)",
      "--shadow-color": "rgba(212, 175, 55, 0.1)",
      "--hover-bg": "#2E2E2E",
      "--success": "#4ADE80",
      "--error": "#F87171",
      "--warning": "#D4AF37",
    },
  },

  // 🌅 Sunset Vibes
  sunsetVibes: {
    id: "sunsetVibes",
    name: "Sunset Vibes",
    icon: "🌅",
    colors: {
      "--bg-primary": "#1A0A1E",
      "--bg-secondary": "#2D1233",
      "--bg-card": "#3A1940",
      "--bg-input": "#4A2050",
      "--text-primary": "#FFF0E5",
      "--text-secondary": "#C49DB0",
      "--accent-primary": "#FF6B35",
      "--accent-secondary": "#FF3CAC",
      "--accent-highlight": "#FFD93D",
      "--border-color": "#4A2050",
      "--btn-gradient-start": "#FF6B35",
      "--btn-gradient-end": "#FF3CAC",
      "--btn-glow": "rgba(255, 107, 53, 0.4)",
      "--shadow-color": "rgba(255, 60, 172, 0.1)",
      "--hover-bg": "#3A1940",
      "--success": "#4ADE80",
      "--error": "#FF4444",
      "--warning": "#FFD93D",
    },
  },
};

export const DEFAULT_THEME = "darkCosmic";
